#!/bin/bash
sudo docker version
sudo docker compose up -d
echo "Hi, I'm sleeping for 60 seconds..."
sleep 60
sudo docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > initdb.sql

